### ISSUE TITLE
Tried adding a movie to Radarr, got error in console

### ISSUE THREAD

**Issue by mancube** [mgdigital/rarbg-selfhosted#17]
time="2023-06-25T16:56:55Z" level=error msg="Failed to handle request" error="sql: Scan error on column index 5, name \"size\": converting NULL to uint64 is unsupported"

**Comment by mgdigital** [comment]
Thanks, just released a fix for this. It seems like a small number of items in the DB have a size of null. I've excluded these from the results rather than handling a null size as it's only 0.2% of items in the DB...
