### ISSUE TITLE
[Question] How to check seeders/leechers ?

### ISSUE THREAD

**Issue by Elu43** [mgdigital/rarbg-selfhosted#20]
Hello, thank you very much for your work, I have your software running, I added the source in prowlarr and I can see releases in Radarr.

But in radarr on the seeders/leechers column, I only have "-/-" (unknown). Is there a way to see them ? Because without this, Radarr considers these releases as low priority in comparison of other trackers, and therefore there are never automatically picked.

Also, what is the purpose of the "trackers.txt" file ?

Thank you very much.

**Comment by mgdigital** [comment]
Thanks!

The RARBG backup database doesn't include any data about seeders and leechers. The job of a tracker is to keep track of how many users are currently seeding and leeching, and that tracker has now shut down. The only way to know the S/L for a torrent is to add it to your client and see what peers it finds. The purpose of `trackers.txt` is to add a list of trackers to generated magnet links, increasing your chances of finding peers. You can configure the minimum seeders requirement within each indexer within Radarr.
