### ISSUE TITLE
Docker image isn't updated?

### ISSUE THREAD

**Issue by mancube** [mgdigital/rarbg-selfhosted#21]
I keep trying to get the new version and pull the image with the fixes, but I get the same old 0.0.4 one

**Comment by mgdigital** [comment]
Hi, the latest Docker image is at 0.0.5 https://github.com/mgdigital/rarbg-selfhosted/pkgs/container/rarbg-selfhosted

**Comment by mancube** [comment]
It was an oversight on my part, I pulled the image but the Portainer container just decided to keep using the old one, removed the container fully and made a new one, everything went fine...
