### ISSUE TITLE
Unclear how trackers.txt work

### ISSUE THREAD

**Issue by Miuccia7** [mgdigital/rarbg-selfhosted#22]
See title. What can I do with the trackers.txt file?

**Comment by mgdigital** [comment]
The trackers.txt file contains a list of trackers that are added to each magnet link

**Comment by Miuccia7** [comment]
I've put three UDP-trackers in the file, each on one line. In my download client, they do not show up in the tracker list on new torrents.

I'm at Synology, with the DSM Download Station as download client.

**Comment by Miuccia7** [comment]
It works now, spontaniously. Thanks!
