### ISSUE TITLE
Is this compatible with ARM machine?

### ISSUE THREAD

**Issue by xiNeRoar** [mgdigital/rarbg-selfhosted#23]
as the title, when I am trying to host it on my ARM machine, the below message comes up;

exec /rarbg-selfhosted: exec format error

therefore I suspect how is this repo compatibility with ARM machine

**Comment by mgdigital** [comment]
Hi, I developed this on an ARM machine and have run it on M1 and M2 Macs without any issue. I've never encountered this error; maybe ensure your Docker is up-to-date.
